version: '3.8'

services:
  # Login Service
  auth-service:
    build: ./path/to/login-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres-db
    networks:
      - auth-network

  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: toto
    volumes:
      - ./path/to/login-service/postgres-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - auth-network

  # Score Service
  score-app:
    build: ./path/to/score-service
    ports:
      - "3005:3005"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./path/to/score-service/data/redis:/data
    networks:
      - mynetwork
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - mynetwork
    restart: always
    volumes:
      - ./path/to/score-service/data/redisinsight:/db
    environment:
      - REDISINSIGHT_HOST=0.0.0.0

  # Motus Service
  motus:
    build: ./path/to/motus-service
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  auth-network:
  mynetwork:

volumes:
  postgres-data:
