version: '3.8'

services:
  # Login Service
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: toto
    volumes:
      - ./login/postgres-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - auth-network

  auth-service:
    build: ./login
    ports:
      - "3002:3002"
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL=postgres://postgres-db:toto@db:5432/postgres
    networks:
      - auth-network


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./Score/data/redis:/data
    networks:
      - motus-network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: always
    volumes:
      - ./Score/data/redisinsight:/db
    environment:
      - REDISINSIGHT_HOST=0.0.0.0
    networks:
      - motus-network

  score-app:
    build: ./Score
    ports:
      - "3005:3005"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - motus-network
  motus1:
    build: ./Motus
    ports:
      - "4001:4000"
    environment:
      - PORT=4000
    networks:
      - motus-network

  motus2:
    build: ./Motus
    ports:
      - "4002:4000"
    environment:
      - PORT=4000
    networks:
      - motus-network

  # HAProxy Service
  haproxy:
    image: haproxy:latest
    container_name: my-haproxy-instance
    ports:
      - "3000:3000"  # Assuming HAProxy is configured to listen on port 3000
    networks:
      - motus-network
    volumes:
      - ./Motus/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  auth-network:
  motus-network:

volumes:
  postgres-data: