version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./data/redis:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: always
    volumes:
      - ./data/redisinsight:/db
    environment:
      - REDISINSIGHT_HOST=0.0.0.0
  score-app:
    build: .
    ports:
      - "3005:3005"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
