version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - redis-net
    restart: always
    volumes:
      - ./data/redis:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - redis-net
    restart: always
    volumes:
      - ./data/redisinsight:/db
    environment:
      - REDISINSIGHT_HOST=0.0.0.0

networks:
  redis-net:
    driver: bridge